/* 
The AWR points are generated by edb360.7a and resides in the edb360 output directory
This js/edb360_awr_points.js loads the generated edb360 generated edb360_awr_points.js
assumed to be in the parent directory where the sqld360 file resides. 
*/

function include(file) { 
  
  var script  = document.createElement('script'); 
  script.src  = file; 
  script.type = 'text/javascript'; 
  script.defer = true; 
  
  document.getElementsByTagName('head').item(0).appendChild(script); 
  
} 
  
/* Include Many js files */
include('../edb360_awr_points.js');