SET VER OFF FEED OFF ECHO OFF HEA OFF TIMI OFF TIM OFF LONG 800000 LONGC 2000 LIN 2000 TRIMS ON TRIM ON NEWP 1 PAGES 1000 RECSEP WR SQLBL OFF BLO ON 
CL COL

EXEC DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SEGMENT_ATTRIBUTES', &&_md_segment_attr.);
EXEC DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', &&_md_storage.);
EXEC DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'TABLESPACE', &&_md_tablespace.);
EXEC DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'CONSTRAINTS_AS_ALTER', &&_md_const_as_alter.);
EXEC DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', &&_md_sql_terminator.);
